config/routes.rb
Rails.application.routes.draw do

  # Our homepage is processed by the static controller's index action.
  root 'static#index'

  get 'logout', to:'sessions#destroy', as:'logout'
  get 'login', to:'sessions#new', as: 'login'
  get 'signup' => "users#new", :as => "signup"
  get 'users/confirm' => 'users#confirm'
  get 'users/invalid_request' => 'users#invalid_request'
  get 'users/forgot' => 'users#forgot'
  post 'users/reset' => 'users#reset'
  get 'users/reauth' => 'users#reauth'
  patch 'users/reauth_submit' => 'users#reauth_submit'
  #match '/auth/:provider/callback', :to => 'sessions#create',via: [:get, :post]
  #match '/auth/failure', :to => 'sessions#failure',via: [:get, :post]

  resources :publications

  #root to: 'application'
  resources :users

  resources :sessions
  #root to: 'sessions#new'
  #root 'sessions#create'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/publication.rb
class Publication < ActiveRecord::Base
   searchable do
     text :title
   end
mount_uploader :article, ArticleUploader

has_many :authorships
has_many :users, through: :authorships

end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :force_authenticate
  before_action :set_publication, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction


  # GET /publications
  # GET /publications.json
  def index
    @search = Publication.order(sort_column+ ' ' + sort_direction).search do
      fulltext params[:search]
     end
  @publications = @search.results
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(publication_params)
    params[:publication][:user_ids].each do |user_id|
      if user_id != ""
        temp_user = User.find(user_id)
        @publication.users << temp_user
      end
    end
    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


   def sort_column
     Publication.column_names.include?(params[:sort]) ? params[:sort] : "Title"
   end
 
   def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
   end
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

  private
  def sort_column
    Publication.column_names.include?(params[:sort]) ? params[:sort] : "Title"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_publication
    @publication = Publication.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def publication_params
    params.require(:publication).permit(:title, :article, :user_ids, :year)
  end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= form_for(@publication) do |f| %>
  <% if @publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
      <% @publication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
      <%= f.label :article %><br>
      <%= f.file_field :article, multiple: true, name: "publication[article]" %>
  </div>
  <div class="field">
    <%= f.label :user_ids %><br>
    <%= f.collection_select :user_ids, User.order(:first), :id, :full_name, {}, {multiple: true, id: "author_select"}  %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
$("#author_select").chosen({
  width: '250px',
  no_results_text: 'No authors found.'
});
</script>

app/views/publications/edit.html.erb
<h1>Editing publication</h1>

<%= render 'form' %>

<%= link_to 'Show', @publication %> |
<%= link_to 'Back', publications_path %>

app/views/publications/index.html.erb
<div id="center_container">
<h1>Listing publications</h1>
<%= form_tag publications_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>
<table class = "pretty">
  <tr>
    <th><%= sortable "title"%></th>
    <th><%= sortable "users_ids.last","Authors"%></th>
    <th><%= sortable "year" %></th>
  </tr>
    <% for publication in @publications %>
    <tr>
        <td><%= publication.title %></td>
        <td><ul>
        <% publication.users.each do |user| %>
          <li><%=user.last %>, <%=user.first%></li>
        <%end%>
        </ul>
        </td>
	<td><%= publication.year %></td>
        <td><%= link_to 'Show', publication %></td>
        <td><%= link_to 'Edit', edit_publication_path(publication) %></td>
        <td><%= link_to 'Destroy', publication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
</table>

<br>

<%= link_to 'New Publication', new_publication_path, id: "new_publication_link", remote: true %>
<script id="template-upload" type="text/x-tmpl">
<div class="upload">
    {%=o.name%}
    <div class="progress"><div class="bar" style="width: 0%"></div></div>
</div>
</script>
<script type="text/javascript">_minimize();</script>
</div>

app/views/publications/new.html.erb
<h1>Upload Publications</h1>

<%= render 'form' %>

<%= link_to 'Back', publications_path %>

app/views/publications/new.js.erb
$("#new_publication_link").hide().after('<%= j render("form") %>');
$('#new_publication').fileUpload({
    add: function(e, data) {
        data.context = $(tmpl("template-upload", data.files[0]))
        $("#new_publication").append(data.context)
        data.submit();
    },

    progress: function(e, data) {
        if (data.context != null && data.context != undefined) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            data.context.find('.bar').css('width', progress + '%');
        }
    }
});

app/views/publications/search.html.erb
<div id="center_container">
<%= form_tag publications_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>
<h1>Listing publications</h1>
<table class = "pretty">
  <tr>
    <th><%= sortable "title"%></th>
    <th><%= sortable "users_ids.last","Authors"%></th>
    <th><%= sortable "year" %></th>
  </tr>
    <% for publication in @publications %>
    <tr>
        <td><%= publication.title %></td>
        <td><ul>
        <% publication.users.each do |user| %>
          <li><%=user.last %>, <%=user.first%></li>
        <%end%>
        </ul>
        </td>
	<td><%= publication.year %></td>
        <td><%= link_to 'Show', publication %></td>
        <td><%= link_to 'Edit', edit_publication_path(publication) %></td>
        <td><%= link_to 'Destroy', publication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
</table>

<br>

<%= link_to 'New Publication', new_publication_path, id: "new_publication_link", remote: true %>
<script id="template-upload" type="text/x-tmpl">
<div class="upload">
    {%=o.name%}
    <div class="progress"><div class="bar" style="width: 0%"></div></div>
</div>
</script>
<script type="text/javascript">_minimize();</script>
</div>

app/views/publications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @publication.title %>
</p>

Authors:
  <ul><% @publication.users.each do |author| %>
    <li><%= full_name author %></li>
  <% end %></ul>

<strong>Year:</strong>
  <%= @publication.year%>

<a href="<%= @publication.article %>">Download</a> |
<%= link_to 'Edit', edit_publication_path(@publication) %> |
<%= link_to 'Back', publications_path %>

<div id="disqus_thread" style="width: 800px;"></div>
<script type="text/javascript">
var disqus_identifier = '<%= (@publication.title + "-" + @publication.created_at.to_s) %>';
var disqus_shortname = 'facultyrepublic'; // required: replace example with your forum shortname

/* * * DON'T EDIT BELOW THIS LINE * * */
(function() {
  var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
  dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
  (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>