config/routes.rb
Rails.application.routes.draw do

  # Our homepage is processed by the static controller's index action.
  root 'static#index'

  get 'logout', to:'sessions#destroy', as:'logout'
  get 'login', to:'sessions#new', as: 'login'
  get 'signup' => "users#new", :as => "signup"
  get 'users/confirm' => 'users#confirm'
  get 'users/invalid_request' => 'users#invalid_request'
  get 'users/forgot' => 'users#forgot'
  post 'users/reset' => 'users#reset'
  get 'users/reauth' => 'users#reauth'
  patch 'users/reauth_submit' => 'users#reauth_submit'
  #match '/auth/:provider/callback', :to => 'sessions#create',via: [:get, :post]
  #match '/auth/failure', :to => 'sessions#failure',via: [:get, :post]

  resources :publications

  #root to: 'application'
  resources :users

  resources :sessions
  #root to: 'sessions#new'
  #root 'sessions#create'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
#has_many :authorizations
#has_many :publishes
has_secure_password
validates_uniqueness_of :email
#attr_accessible :email, :password, :password_confirmation

validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_presence_of :first
  validates_presence_of :last

  has_many :authorships
  has_many :publications, through: :authorships
# def self.authenticate(email, password)
#   user = find_by_email(email)
#   if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
#     user
#   else
#     nil
#   end
# end


def full_name
  "#{first} #{last}"
end

#attr_accessible :email, :password, :password_confirmation
#validates :name, :email, :presence => true

#def self.create_with_omniauth(auth)
 # create! do |user|
  #  user.provider = auth["provider"]
   # user.uid = auth["uid"]
    #user.name = auth["user_info"]["name"]
   #end
  #end

#def add_provider(auth_hash)
  # Check if the provider already exists, so we don't add it twice
 # unless authorizations.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
  #  Authorization.create :user => self, :provider => auth_hash["provider"], :uid => auth_hash["uid"]
  #end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
   end

   def create
     @user = User.new(user_params)
     @user.verified = false
     @user.confirmation_token = SecureRandom.urlsafe_base64(nil, false)
     if @user.save
        UserMailer.new_user_confirmation(@user).deliver
        session[:user_id] = @user.id
        redirect_to publications_url, :notice =>"Thank you for signing up! Please confirm your email."
     else
        render :new
     end
   end

   def show
     # show profile
     @user = User.find_by_id(params[:id])
   end

   def confirm
     user = User.find_by_confirmation_token(params[:token])
     if user.nil?
       redirect_to users_invalid_request_url, :notice => "Unfortunately, the token provided does not seem authentic."
     else
       user.verified = true
     end
   end

   def invalid_request

   end

   def forgot
     @user = User.new
   end

   def reset
     @user = User.find_by_email(params[:user][:email])
    #  raise @user
     if @user.nil?
       render "forgot", notice: "There is no user with that email."
     else
       @user.forgot_password_token = SecureRandom.urlsafe_base64(nil, false)
       if @user.save
         UserMailer.user_password_reset(@user).deliver
         redirect_to root_url
       end
     end
   end

   def reauth
     @user = User.find_by_forgot_password_token(params[:token])
     if @user.nil?
       redirect_to users_invalid_request_url, :notice => "Unfortunately, the token provided does not seem authentic."
     end
   end

   def reauth_submit
     @user = User.find_by_forgot_password_token(params[:user][:token])
      if @user.update(password_params)
         redirect_to publications_url, notice: 'Account was successfully updated.'
      else
        render "forgot"
     end
   end


private

   def user_params
       params.require(:user).permit(:password, :password_confirmation, :last, :first, :email, :article)
   end

   def password_params
     params.require(:user).permit(:password, :password_confirmation)
   end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_form.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
     <div class= "error_messages">
       <h2>Form is invalid</h2>
       <ul>
          <% @user.errors.full_messages.each do |message| %>
          <li><%=message%></li>
          <% end %>
       </ul>
      </div>
<% end %>

  <div class = "field">
    <%= f.label :first %> <br />
    <%= f.text_field :first %>
  </div>
  <div class = "field">
    <%= f.label :last %> <br />
    <%= f.text_field :last %>
  </div>
  <div class = "field">
   <%= f.label :email %> <br />
   <%= f.text_field :email %>
  </div>
  <div class = "field">
    <%= f.label :password %> <br />
    <%= f.password_field :password %>
  </div>
  <div class = "field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
   </div>
  <div class="actions"><%= f.submit%></div>
<% end %>

app/views/users/confirm.html.erb
<h1>Congrats!</h1>
<p>You are all verified!</p>
<%= link_to "Click here to go to Publications", publications_url %>

app/views/users/forgot.html.erb
<h1>Forgot Password</h1>

<%= form_for @user, url: users_reset_path(params[:token]) do |f| %>
<p>
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</p>
<p class="button"><%= f.submit %></p>
<% end %>

app/views/users/invalid_request.html.erb
<h1>Hold on a Second!</h1>
<p>Somebody could be doing something nasty.  Your authentication token is
   invalid.  Please request another one below.</p>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/reauth.html.erb
<h1>Password Recovery</h1>

<%= form_for @user, url: users_reauth_submit_path do |f| %>
<div class = "field">
  <%= f.label :password %> <br />
  <%= f.password_field :password %>
</div>
<div class = "field">
  <%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %>
</div>
  <%= f.hidden_field :token, value: @user.forgot_password_token %>
<p class="button"><%= f.submit %></p>
<% end %>

app/views/users/show.html.erb
<table>
  <tr>
    <th width="350px">
      <%= image_tag avatar_url(@user) %>
      <h2><%= full_name @user %></h2>
      <%= mailto_link @user %>
    </th>
    <td style="vertical-align:top;">
      <h4>Publications</h4>
      <ul>
        <% if @user.publications.count < 1 %>
          <li><i>You haven't written anything yet.</i></li>
        <% else %>
          <% @user.publications.each do |publication| %>
            <% pretty_publication_with_link publication %>
          <% end %>
        <% end %>
    </td>
  </tr>
</table>