config/routes.rb
Rails.application.routes.draw do

  # Our homepage is processed by the static controller's index action.
  root 'static#index'

  get 'logout', to:'sessions#destroy', as:'logout'
  get 'login', to:'sessions#new', as: 'login'
  get 'signup' => "users#new", :as => "signup"
  get 'users/confirm' => 'users#confirm'
  get 'users/invalid_request' => 'users#invalid_request'
  get 'users/forgot' => 'users#forgot'
  post 'users/reset' => 'users#reset'
  get 'users/reauth' => 'users#reauth'
  patch 'users/reauth_submit' => 'users#reauth_submit'
  #match '/auth/:provider/callback', :to => 'sessions#create',via: [:get, :post]
  #match '/auth/failure', :to => 'sessions#failure',via: [:get, :post]

  resources :publications

  #root to: 'application'
  resources :users

  resources :sessions
  #root to: 'sessions#new'
  #root 'sessions#create'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FacultyRepublic</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Cabin|PT+Serif:400,700' rel='stylesheet' type='text/css'>
</head>
<body>
  <div id="header">
      <div id="logo" data-expanded="false"><img alt="Logo" id="logo" src="/assets/logo_hover.svg" style="width: 50px; height: 50px;"></div>
      <!-- <%= image_tag "logo.svg", id: "logo" %> -->
      <div id="slogan" style="display: none;">In available notitia radix</div>
    <!-- <table style="width:100%; padding-left:23cm;">
      <th></th> -->
      <div id = "user_nav">
        <%= image_tag "searchBar.png", id: "searchBar", alt: "searchBar" %>
          <p>
  </p>
        <a href="/logout"><div id="logout" class="minibutton">Logout</div></a>
      </div>

    <!--  <th></th>
    </table> -->
  </div>

  <div id = "container"><div id="box">
      <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>

          <%= yield %>
  </div>
</div>
</body>
</html>

app/views/layouts/statout.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>FacultyRepublic</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Cabin|PT+Serif:400,700' rel='stylesheet' type='text/css'>
</head>
<body data-no-turbolink>
    <div id="header">
        <div id="logo" data-expanded="true"><img alt="Logo" id="logo" src="/assets/logo.svg" style="width: 130px; height: 130px;"></div>
        <!-- <%= image_tag "logo.svg", id: "logo" %> -->
        <div id="slogan">In available notitia radix</div>
        <!-- <table style="width:100%; padding-left:23cm;">
        <th></th> -->
        <!--  <th></th> -->
        <div id = "user_nav">
            <a href="/login"><div id="login" class="minibutton">Login</div></a>
            <a href="/users/new"><div id="register" class="minibutton">Sign Up</div></a>
        </div>
    <!--    <%= link_to "Sign Up", new_user_path%> or
        <%= link_to "Log In", new_session_path %>-->
    </div>
    </table> -->
</div>

<div id = "container">
    <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>

    <%= yield %>

</div>
</body>
</html>